ESI_WORD_DICT = {

    # ── ESI LEVEL 1 — IMMEDIATE / LIFE THREATENING ──────────────────────────
    # Patient may die without instant intervention
    "cardiac arrest":           1,
    "respiratory arrest":       1,
    "pulseless electrical":     1,
    "ventricular fibrillation": 1,
    "asthmaticus unresponsive": 1,
    "status epilepticus":       1,
    "epilepticus refractory":   1,
    "coma unknown":             1,
    "hypothyroid coma":         1,
    "collapse unresponsive":    1,
    "mva unresponsive":         1,
    "hypoglycaemia unresponsive":1,
    "unresponsive":             1,
    "cardiac":                  1,
    "arrest":                   1,
    "drowning":                 1,
    "near drowning":            1,
    "gunshot wound":            1,
    "traumatic amputation":     1,
    "traumatic brain":          1,
    "massive transfusion":      1,
    "tension pneumothorax":     1,
    "airway obstruction":       1,
    "airway compromise":        1,
    "locked syndrome":          1,
    "pulseless":                1,
    "fulminant hepatic":        1,
    "fulminant hepatitis":      1,

    # ── ESI LEVEL 2 — EMERGENT / HIGH RISK ──────────────────────────────────
    # High risk of deterioration, needs fast workup
    "acute stemi":              2,
    "acute nstemi":             2,
    "nstemi":                   2,
    "stemi cardiogenic":        2,
    "aortic dissection":        2,
    "aortic aneurysm":          2,
    "ruptured aortic":          2,
    "ruptured ectopic":         2,
    "ectopic pregnancy":        2,
    "acute stroke":             2,
    "ischaemic stroke":         2,
    "massive ischaemic":        2,
    "stroke herniation":        2,
    "herniation signs":         2,
    "meningococcal septicaemia":2,
    "meningococcal purpura":    2,
    "bacterial meningitis":     2,
    "meningitis suspected":     2,
    "septic shock":             2,
    "cardiogenic shock":        2,
    "toxic shock":              2,
    "anaphylaxis bronchospasm": 2,
    "anaphylaxis urticaria":    2,
    "anaphylaxis":              2,
    "severe anaphylaxis":       2,
    "severe allergic":          2,
    "hypertensive emergency":   2,
    "severe hypertensive":      2,
    "acute adrenal":            2,
    "adrenal crisis":           2,
    "adrenal insufficiency":    2,
    "diabetic ketoacidosis":    2,
    "dka":                      2,
    "hyperosmolar hyperglycaemic": 2,
    "hyperglycaemic crisis":    2,
    "suicidal ideation":        2,
    "suicidal attempt":         2,
    "active suicidal":          2,
    "ideation plan":            2,
    "attempt ongoing":          2,
    "self harm haemorrhage":    2,
    "severe self":              2,
    "acute psychosis":          2,
    "excited delirium":         2,
    "psychosis violence":       2,
    "altered mental":           2,
    "acute altered":            2,
    "sepsis altered":           2,
    "confusion elderly":        2,
    "haemodynamically unstable":2,
    "haemodynamic instability": 2,
    "uncontrolled haemodynamic":2,
    "haemodynamic compromise":  2,
    "gi haemorrhage":           2,
    "haematemesis":             2,
    "bleed haematemesis":       2,
    "vomiting blood":           2,
    "actively bleeding":        2,
    "massive lower":            2,
    "massive pulmonary":        2,
    "large pulmonary":          2,
    "pulmonary embolism":       2,
    "testicular torsion":       2,
    "ovarian torsion":          2,
    "torsion shock":            2,
    "globe rupture":            2,
    "retinal detachment":       2,
    "central retinal":          2,
    "retinal artery":           2,
    "acute angle":              2,
    "angle closure":            2,
    "severe acute":             2,
    "severe cardiogenic":       2,
    "acute mastoiditis":        2,
    "epiglottitis suspected":   2,
    "retropharyngeal abscess":  2,
    "peritonsillar abscess":    2,
    "abscess airway":           2,
    "abscess trismus":          2,
    "necrotising fasciitis":    2,
    "necrotising infection":    2,
    "fasciitis rapid":          2,
    "rapidly spreading":        2,
    "rapid spread":             2,
    "compartment syndrome":     2,
    "orbital compartment":      2,
    "spinal cord":              2,
    "cord injury":              2,
    "open fracture":            2,
    "fracture haemodynamically":2,
    "pelvic fracture":          2,
    "femur fracture":           2,
    "open femur":               2,
    "multi trauma":             2,
    "blunt thoracic":           2,
    "penetrating abdominal":    2,
    "penetrating neck":         2,
    "fractures airway":         2,
    "multi organ":              2,
    "organ failure":            2,
    "organ dysfunction":        2,
    "failure hypoxia":          2,
    "respiratory failure":      2,
    "renal failure":            2,
    "hepatic failure":          2,
    "heart failure":            2,
    "decompensated heart":      2,
    "severe dyspnoea":          2,
    "dyspnoea rest":            2,
    "severe pain":              2,
    "syncope":                  2,
    "near syncope":             2,
    "collapse":                 2,
    "thyroid storm":            2,
    "acute mania":              2,
    "mania risk":               2,
    "alcohol withdrawal":       2,
    "drug overdose":            2,
    "deliberate overdose":      2,
    "overdose collapse":        2,
    "overdose unknown":         2,
    "severe malaria":           2,
    "stevens johnson":          2,
    "toxic epidermal":          2,
    "epidermal necrolysis":     2,
    "bullous pemphigoid":       2,
    "pemphigoid acute":         2,
    "eczema herpeticum":        2,
    "status asthmaticus":       2,
    "severe asthma":            2,
    "mesenteric ischaemia":     2,
    "acute mesenteric":         2,
    "bowel perforation":        2,
    "perforation peritonitis":  2,
    "priapism ischaemia":       2,
    "urosepsis":                2,

    # ── ESI LEVEL 3 — URGENT ────────────────────────────────────────────────
    # Stable but needs multiple resources / monitoring
    "chest pain":               3,
    "pleuritic chest":          3,
    "exertional chest":         3,
    "chest discomfort":         3,
    "chest tightness":          3,
    "atrial fibrillation":      3,
    "af stable":                3,
    "palpitations":             3,
    "dyspnoea exertion":        3,
    "dyspnoea":                 3,
    "shortness":                3,
    "tightness dyspnoea":       3,
    "abdominal pain":           3,
    "acute abdomen":            3,
    "blunt abdominal":          3,
    "abdominal stab":           3,
    "abdominal cramping":       3,
    "appendicitis":             3,
    "renal colic":              3,
    "flank pain":               3,
    "stab wound":               3,
    "fracture":                 3,
    "bone fracture":            3,
    "rib fracture":             3,
    "ankle fracture":           3,
    "radius fracture":          3,
    "distal radius":            3,
    "closed ankle":             3,
    "fall height":              3,
    "fall injury":              3,
    "head injury":              3,
    "significant head":         3,
    "significant mechanism":    3,
    "high speed":               3,
    "injury gcs":               3,
    "injury neurological":      3,
    "neurological deficit":     3,
    "focal deficits":           3,
    "focal":                    3,
    "limb weakness":            3,
    "transient limb":           3,
    "facial droop":             3,
    "droop resolved":           3,
    "seizure":                  3,
    "ongoing seizure":          3,
    "sepsis":                   3,
    "sepsis signs":             3,
    "wound sepsis":             3,
    "severe fever":             3,
    "high fever":               3,
    "fever unknown":            3,
    "dengue fever":             3,
    "dengue":                   3,
    "malaria":                  3,
    "pancreatitis":             3,
    "acute pancreatitis":       3,
    "pancreatitis organ":       3,
    "cellulitis systemic":      3,
    "orbital cellulitis":       3,
    "spreading cellulitis":     3,
    "infected wound":           3,
    "wound infection":          3,
    "laceration actively":      3,
    "scalp laceration":         3,
    "facial laceration":        3,
    "deep dog":                 3,
    "dog bite":                 3,
    "bite wound":               3,
    "significant blunt":        3,
    "thoracic trauma":          3,
    "neck trauma":              3,
    "facial trauma":            3,
    "trauma haemothorax":       3,
    "haemothorax":              3,
    "pneumothorax":             3,
    "haemoptysis significant":  3,
    "haematuria significant":   3,
    "bloody diarrhoea":         3,
    "gi bleed":                 3,
    "upper gi":                 3,
    "lower gi":                 3,
    "diarrhoea":                3,
    "vomiting":                 3,
    "bilious vomiting":         3,
    "nausea vomiting":          3,
    "dehydration moderate":     3,
    "severe dehydration":       3,
    "headache":                 3,
    "thunderclap headache":     3,
    "thunderclap":              3,
    "migraine photophobia":     3,
    "migraine":                 3,
    "acute vertigo":            3,
    "vertigo vomiting":         3,
    "dizziness":                3,
    "positional dizziness":     3,
    "confusion":                3,
    "delirium":                 3,
    "obtundation":              3,
    "hypoglycaemia":            3,
    "severe hypoglycaemia":     3,
    "hyperglycaemia":           3,
    "electrolyte disturbance":  3,
    "electrolyte imbalance":    3,
    "abnormal vitals":          3,
    "hypothermia moderate":     3,
    "hypothermia":              3,
    "hypoxia":                  3,
    "dysphagia":                3,
    "severe tonsillitis":       3,
    "tonsillitis dysphagia":    3,
    "peritonitis":              3,
    "pyelonephritis fever":     3,
    "pyelonephritis":           3,
    "urinary retention":        3,
    "acute urinary":            3,
    "vaginal bleeding":         3,
    "ectopic":                  3,
    "psychiatric decompensation":3,
    "acute psychiatric":        3,
    "substance intoxication":   3,
    "intoxication":             3,
    "overdose":                 3,
    "self harm":                3,
    "severe self":              3,
    "pain":                     3,
    "severe pain":              3,
    "scrotal pain":             3,
    "worsening":                3,
    "worsening hours":          3,
    "rigors":                   3,
    "diaphoresis":              3,
    "diaphoresis arm":          3,
    "bleeding":                 3,
    "haemorrhage":              3,
    "infection":                3,
    "fever":                    3,
    "nausea":                   3,
    "shingles":                 3,
    "shingles pain":            3,
    "erythema migrans":         3,
    "cellulitis":               3,
    "wound":                    3,
    "laceration":               3,
    "trauma":                   3,

    # ── ESI LEVEL 4 — LESS URGENT ───────────────────────────────────────────
    # One resource needed, stable condition
    "moderate headache":        4,
    "chronic headache":         4,
    "headache review":          4,
    "migraine recurrence":      4,
    "mild nausea":              4,
    "mild fever":               4,
    "mild dyspnoea":            4,
    "mild dysuria":             4,
    "mild abdominal":           4,
    "mild bloating":            4,
    "mild chest":               4,
    "mild confusion":           4,
    "mild dehydration":         4,
    "mild epistaxis":           4,
    "mild hypoglycaemia":       4,
    "mild gastroenteritis":     4,
    "mild wheeze":              4,
    "mild urinary":             4,
    "moderate epistaxis":       4,
    "epistaxis controlled":     4,
    "epistaxis":                4,
    "rash":                     4,
    "allergic rash":            4,
    "skin rash":                4,
    "contact dermatitis":       4,
    "dermatitis":               4,
    "urticaria":                4,
    "eczema":                   4,
    "conjunctivitis":           4,
    "corneal abrasion":         4,
    "eye irritation":           4,
    "itchy eyes":               4,
    "mild eye":                 4,
    "mild photophobia":         4,
    "mild sore":                4,
    "sore throat":              4,
    "throat moderate":          4,
    "tonsillitis":              4,
    "otitis media":             4,
    "ear pain":                 4,
    "sinusitis":                4,
    "productive cough":         4,
    "cough":                    4,
    "chronic cough":            4,
    "nasal congestion":         4,
    "congestion runny":         4,
    "runny nose":               4,
    "urti mild":                4,
    "viral urti":               4,
    "ankle sprain":             4,
    "lateral ankle":            4,
    "knee injury":              4,
    "shoulder pain":            4,
    "shoulder dislocation":     4,
    "muscle strain":            4,
    "muscle soreness":          4,
    "sprain":                   4,
    "bruised knee":             4,
    "minor abrasion":           4,
    "abrasion":                 4,
    "minor facial":             4,
    "minor head":               4,
    "minor wound":              4,
    "minor skin":               4,
    "small cut":                4,
    "cut wound":                4,
    "superficial laceration":   4,
    "minor joint":              4,
    "joint ache":               4,
    "swollen joint":            4,
    "hot swollen":              4,
    "dysuria":                  4,
    "dysuria systemic":         4,
    "uncomplicated uti":        4,
    "uti symptoms":             4,
    "uti":                      4,
    "urinary symptoms":         4,
    "genital discharge":        4,
    "mild":                     4,
    "minor":                    4,
    "low grade":                4,
    "afebrile":                 4,
    "tick bite":                4,
    "insect bite":              4,
    "insect sting":             4,
    "ingrown toenail":          4,
    "toenail infected":         4,
    "skin tag":                 4,
    "splinter removal":         4,
    "acne":                     4,
    "sunburn":                  4,
    "dry skin":                 4,
    "bloating":                 4,
    "constipation":             4,
    "ibs":                      4,
    "chronic flare":            4,
    "anxiety flare":            4,
    "panic attack":             4,
    "low mood":                 4,
    "depressive episode":       4,
    "chronic anxiety":          4,
    "insomnia severe":          4,
    "fatigue":                  4,
    "weight loss":              4,
    "hearing loss":             4,
    "blocked ear":              4,
    "ear wax":                  4,
    "wax removal":              4,
    "pelvic":                   4,
    "vaginal":                  4,
    "contraception":            4,

    # ── ESI LEVEL 5 — NON-URGENT ────────────────────────────────────────────
    # No resources needed, admin or routine queries
    "prescription refill":      5,
    "antihypertensive refill":  5,
    "repeat prescription":      5,
    "refill request":           5,
    "refill":                   5,
    "glasses prescription":     5,
    "drop prescription":        5,
    "medical certificate":      5,
    "certificate request":      5,
    "cardiology paperwork":     5,
    "paperwork":                5,
    "routine check":            5,
    "routine bp":               5,
    "routine sti":              5,
    "bp monitoring":            5,
    "blood pressure":           5,
    "glucose monitoring":       5,
    "blood glucose":            5,
    "general health":           5,
    "general unwell":           5,
    "health question":          5,
    "health medication":        5,
    "management question":      5,
    "diabetes review":          5,
    "diabetes management":      5,
    "medication review":        5,
    "medication adjustment":    5,
    "medication effect":        5,
    "thyroid medication":       5,
    "thyroid related":          5,
    "follow":                   5,
    "stable follow":            5,
    "ibs follow":               5,
    "non urgent":               5,
    "advice":                   5,
    "contraception advice":     5,
    "dietary advice":           5,
    "activity advice":          5,
    "acne advice":              5,
    "hygiene advice":           5,
    "sleep hygiene":            5,
    "exposure advice":          5,
    "travel prophylaxis":       5,
    "post exposure":            5,
    "vaccination":              5,
    "sti screening":            5,
    "screening":                5,
    "referral query":           5,
    "counselling referral":     5,
    "physiotherapy referral":   5,
    "endocrine referral":       5,
    "administrative query":     5,
    "admission query":          5,
    "adjustment query":         5,
    "social admission":         5,
    "prescription query":       5,
    "prescription question":    5,
    "result inquiry":           5,
    "ecg result":               5,
    "memory complaint":         5,
    "non specific":             5,
    "intermittent":             5,
    "check":                    5,
    "wound check":              5,
    "suture removal":           5,
    "tag removal":              5,
    "removal request":          5,
    "splinter":                 5,
}

ESI_LABELS = {
    1: "Immediate",
    2: "Emergent",
    3: "Urgent",
    4: "Less Urgent",
    5: "Non-Urgent"
}